"""Download the three lecture typefaces once, into lectures/_fonts/.

Why: every slide used to <link> fonts.googleapis.com at render time. That makes
the whole deck build depend on the network — and when Google was briefly
unreachable, the webfont gate correctly refused to render all 35 diagrams, after
waiting 20s each. Ten minutes, nothing produced.

Self-hosting removes the dependency entirely and makes renders faster and
byte-for-byte reproducible offline.

Usage:  python fetch_fonts.py          # writes _fonts/*.woff2 + _fonts/fonts.css
"""
from __future__ import annotations
import pathlib, re, urllib.request

ROOT = pathlib.Path(__file__).parent
DEST = ROOT / "_fonts"
DEST.mkdir(exist_ok=True)

# A modern browser UA — otherwise Google serves legacy TTF instead of woff2.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

FAMILIES = {
    "Asap": "Asap:wght@600;700;800",
    "Cabin": "Cabin:wght@400;500;600;700",
    "IBM Plex Mono": "IBM+Plex+Mono:wght@400;500;600",
}


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


blocks: list[str] = []
n_files = 0

for family, spec in FAMILIES.items():
    css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode("utf-8")
    # Keep only the latin / latin-ext subsets — the deck is English, and pulling
    # all ~28 unicode-range subsets per family is what made fonts.check() useless.
    for m in re.finditer(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S):
        subset, face = m.group(1), m.group(2)
        if subset not in ("latin", "latin-ext"):
            continue
        weight = re.search(r"font-weight:\s*(\d+)", face)
        url_m = re.search(r"url\((https://[^)]+\.woff2)\)", face)
        if not (weight and url_m):
            continue
        slug = family.lower().replace(" ", "-")
        fname = f"{slug}-{weight.group(1)}-{subset}.woff2"
        (DEST / fname).write_bytes(get(url_m.group(1)))
        n_files += 1
        local = face.replace(url_m.group(1), fname)
        blocks.append(local.strip())
        print(f"  {fname}")

(DEST / "fonts.css").write_text(
    "/* Self-hosted lecture typefaces. Generated by fetch_fonts.py — do not edit.\n"
    "   Slides reference these instead of fonts.googleapis.com so a render never\n"
    "   depends on the network. Paths are relative to this file. */\n\n"
    + "\n\n".join(blocks) + "\n",
    encoding="utf-8",
)
print(f"\n{n_files} font files + fonts.css -> {DEST}")
